//================================================================================
// MenuIcons.
//
// Holder class for the language settings button's icon (idle + rollover),
// generated by tools/scripts/generate_menu_icons.py to match the stock
// HP2_Menu.Icons style, deployed to $GAMEDIR/HGame/Textures/LangPicker/.
// COMPRESSION=3 (DXT5) keeps the soft alpha edges, same as HGame's own
// alpha HUD icons (e.g. leftPanel).
//================================================================================

class MenuIcons extends Object
	abstract;

#exec Texture Import File=Textures\LangPicker\HP2MenuLanguages.png GROUP=LangPicker Name=HP2MenuLanguages COMPRESSION=3 UPSCALE=1 Mips=0 Flags=0
#exec Texture Import File=Textures\LangPicker\HP2MenuLanguagesOver.png GROUP=LangPicker Name=HP2MenuLanguagesOver COMPRESSION=3 UPSCALE=1 Mips=0 Flags=0
